services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discovery-service:
    build:
      context: .
      dockerfile: ./docker-k8s/Dockerfile.backend
      args:
        SERVICE_NAME: discovery-service
    ports:
      - "8761:8761"

  config-service:

    build:
      context: .
      dockerfile: ./docker-k8s/Dockerfile.backend
      args:
        SERVICE_NAME: config-service
    depends_on:
      - discovery-service
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  gateway-service:
    build:
      context: .
      dockerfile: ./docker-k8s/Dockerfile.backend
      args:
        SERVICE_NAME: gateway-service
    depends_on:
      - discovery-service
      - config-service
    ports:
      - "8887:8887"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  collecte-service:
    build:
      context: .
      dockerfile: ./docker-k8s/Dockerfile.backend
      args:
        SERVICE_NAME: collecte-service
    depends_on:
      - discovery-service
      - config-service
      - kafka
    ports:
      - "8081:8081"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  analyse-service:
    build:
      context: .
      dockerfile: ./docker-k8s/Dockerfile.backend
      args:
        SERVICE_NAME: analyse-service
    depends_on:
      - discovery-service
      - config-service
      - kafka
    ports:
      - "8082:8082"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  frontend:
    build:
      context: .
      dockerfile: ./docker-k8s/Dockerfile.frontend
    ports:
      - "8083:80"
    depends_on:
      - gateway-service
